#!/bin/zsh

# Header Test


flip1="{\"flip\":\"heads\"}"
flip2="{\"flip\":\"tails\"}"
sleep 0.1

expected="200 OK"
((node server.js & sleep 2) && kill $! ) & 
( sleep 1 && result=$(curl http://localhost:5000/app) && sleep 0.1 ; 
[ "$expected" = "$result" ] && echo "Passed header test" || echo "Expected $expected ;\nGot: $result.")

sleep 3

# Port Test
expected="200 OK"
(node server.js --port=3000 & sleep 2; kill $! ) & 
( sleep 1; result=$(curl http://localhost:3000/app); sleep 0.1 ; 
[ "$expected" = "$result" ] && echo "Passed port test" || echo "Expected $expected ;\nGot: $result.")

sleep 3

# Not Found Test
expected="404 NOT"
(node server.js --port=3000 & sleep 2; kill $! ) & 
(sleep 1; result=$(curl http://localhost:3000/app/invalid); sleep 0.1 ;
match=$(echo "$result" | grep "$expected") ; 
[ "$match" = "$result" ] && echo "Passed Not Found Test" || echo "Expected $expected ;\nGot: $result.")
sleep 3

# Flip Test
# expected="{\"raw\":\[\"tails","tails","heads","tails","tails","tails","heads","heads","tails","tails","heads","heads","tails","heads","tails","heads","tails","heads","tails","heads"],"summary":{"tails":11,"heads":9}}"

# (node server.js --port=3000 & sleep 2; kill $! ) & 
# ( sleep 1; result=$(curl http://localhost:3000/app/flip) ; sleep 0.1 ; 
# match=$(echo "$result" | grep -E "$expected") ; 
# [[ "$match" = "$result" && -n $result ]] && echo "Passed Coinflip Test" || echo "Expected $expected ;\nGot: $result.")
# sleep 3

# Multiflip test
expected="{\"flip\":\"(heads|tails)\"}"

(node server.js --port=3000 & sleep 2; kill $! ) & 
( sleep 1; result=$(curl http://localhost:3000/app/flip) ; sleep 0.1 ; 
match=$(echo "$result" | grep -E "$expected") ; 
[[ "$match" = "$result" && -n $result ]] && echo "Passed Multiflip Test" || echo "Expected $expected ;\nGot: $result.")
sleep 3
